<?php
echo "<section id='footer'>";
	echo "<div class='container'>";
		echo "<div class='row'>";
			echo "<div class='col-8 col-12-medium'>";
				echo "<!-- Links -->";
				echo "<section>";
					echo "<h2>Enlaces interesantes</h2>";
					echo "<div>";
						echo "<div class='row'>";
							echo "<div class='col-3 col-12-small'>";
								echo "<ul class='link-list last-child'>";
									echo "<li><a href='javascript: OpenURL('https://www.fcbarcelona.es')'>F.C. Barcelona</a></li>";
									echo "<li><a href='javascript: OpenURL('https://confederaciopenyes.cat/es/inicio/')'>Confederación de Peñas</a></li>";
								echo "</ul>";
							echo "</div>";
							echo "<div class='col-3 col-12-small'>";
								echo "<ul class='link-list last-child'>";
									echo "<li><a href='javascript: OpenURL('https://www.facebook.com/PBMontan/')'>Facebook P.B. Montán</a></li>";
									echo "<li><a href='javascript: OpenURL('https://twitter.com/PBMontan')'>Twitter P.B. Montán</a></li>";
								echo "</ul>";
							echo "</div>";
							echo "<div class='col-3 col-12-small'>";
								echo "<ul class='link-list last-child'>";
									echo "<li><a href='javascript: OpenURL('http://www.montan.es')'>Montán (Web oficial)</a></li>";
									echo "<li><a href='javascript: OpenURL('https://es.wikipedia.org/wiki/Mont%C3%A1n')'>Montán (Wikipedia)</a></li>";
								echo "</ul>";
							echo "</div>";
						echo "</div>";
					echo "</div>";
				echo "</section>";
			echo "</div>";
			echo "<div class='col-4 col-12-medium imp-medium'>";
				echo "<!-- Blurb -->";
				echo "<section>";
					echo "<img src='../images/senyera.png' alt='Senyera' style='vertical-align:middle;'>&nbsp;&nbsp;<a href='../ca/activitats.html'><font size='+2'>Versió en Valencià</font></a>";
				echo "</section>";
			echo "</div>";
		echo "</div>";
	echo "</div>";
echo "</section>";
?>

